CREATE TABLE IF NOT EXISTS credito
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_credito    VARCHAR(50)    NOT NULL,
    numero_nfse       VARCHAR(50)    NOT NULL,
    data_constituicao DATE           NOT NULL,
    valor_issqn       DECIMAL(15, 2) NOT NULL,
    tipo_credito      VARCHAR(50)    NOT NULL,
    simples_nacional  BOOLEAN        NOT NULL,
    aliquota          DECIMAL(5, 2)  NOT NULL,
    valor_faturado    DECIMAL(15, 2) NOT NULL,
    valor_deducao     DECIMAL(15, 2) NOT NULL,
    base_calculo      DECIMAL(15, 2) NOT NULL,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_credito_numero_credito ON credito(numero_credito);
CREATE INDEX idx_credito_numero_nfse ON credito(numero_nfse);
CREATE INDEX idx_credito_data_constituicao ON credito(data_constituicao);

-- Trigger para atualizar updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_credito_updated_at 
    BEFORE UPDATE ON credito 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();